# Azure DevOps pipeline.

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
  - container: mailhog
    image: mailhog:mailhog
    ports: [ "1025" , "8025" ]

# Only manual execution from Azure DevOps portal
trigger: none
pr: none

jobs:
  - job: empty_job
    steps:
      # 1. Set the number of the run
      - task: PowerShell@2
        displayName: Update Run Number
        inputs:
          targetType: 'inline'
          script: '$id = "$(Build.BuildId)"; $date = Get-Date -Format "yyyy.MMdd"; Write-Host "##vso[build.updatebuildnumber]$date.$id"'
  - job: start_container
    steps:
    - script: echo |
        echo $(resources.container.mailhog.type)
        echo $(resources.container.mailhog.registry)
        echo $(resources.container.mailhog.repository)
        echo $(resources.container.mailhog.tag)
        echo $(resources.container.mailhog.digest)
        echo $(resources.container.mailhog.URI)
        echo $(resources.container.mailhog.location)
