# Azure DevOps pipeline for automating purge durable functions history.
# Only specified parameters are applied, policies folder is ignored.
#
# The following parameter needs to be set to identify the Azure subscription :
# - SUBSCRIPTION: PROD-IO-SERVICE-CONN | DEV-IO-SERVICE-CONN
#
# The following pipeline parameters have to be setted for manual execution:
# - SUBSCRIPTION: service connection name
# - DRY_RUN: run pipeline without apply any changes
# - STORAGE_ACCOUNT: storage account name to connect
# - TASK_HUB: taskhub name setted in durable function host.json
# - NO_DATE_FILTER: if true do not apply any date filter (ignore DAYS_BEFORE)
# - DAYS_BEFORE: number of days to apply date filter (negative -> past, positive -> future)
# - NO_STATUS_FILTER: if true do not apply any status filter (ignore LIST_STATUS)
# - LIST_STATUS: filter orchestrator's status

parameters:
  - name: "SUBSCRIPTION"
    displayName: "Select the Azure subscription for which purge durable function history"
    type: string
    default: DEV-IO-SERVICE-CONN
    values:
      - PROD-IO-SERVICE-CONN
      - DEV-IO-SERVICE-CONN

pool:
  vmImage: "ubuntu-latest"

# Only manual execution from Azure DevOps portal
# trigger: none
trigger:
  - master
pr: none

jobs:
  - job: terraform_integrity_check
    steps:
      # 1. Set the number of the run
      - task: PowerShell@2
        displayName: Update Run Number
        inputs:
          targetType: "inline"
          script: '$id = "$(Build.BuildId)"; $date = Get-Date -Format "yyyy.MMdd"; Write-Host "##vso[build.updatebuildnumber]$date.$id"'

      # 2. Install terraform
      - task: AzureCLI@2
        displayName: Install terraform
        inputs:
          azureSubscription: "${{ parameters.SUBSCRIPTION }}"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          failOnStandardError: true
          inlineScript: |
            git clone -q https://github.com/tfutils/tfenv.git $HOME/.tfenv
            ls -la
            echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> $HOME/.bash_profile
            source $HOME/.bash_profile
            tfenv install
