# Azure DevOps pipeline.

pool:
  vmImage: 'ubuntu-latest'

# Only manual execution from Azure DevOps portal
trigger: none
pr: none

jobs:
  - job: empty_job
    steps:
      # 1. Set the number of the run
      - task: PowerShell@2
        displayName: Update Run Number
        inputs:
          targetType: 'inline'
          script: '$id = "$(Build.BuildId)"; $date = Get-Date -Format "yyyy.MMdd"; Write-Host "##vso[build.updatebuildnumber]$date.$id"'
  - job: start_container
    steps:
    - script: |
        docker run --rm hello-world:linux
