# Azure DevOps pipeline for test terraform integrity.
#
# The following parameter needs to be set to identify the Azure subscription :
# - SUBSCRIPTION: PROD-IO-SERVICE-CONN | DEV-IO-SERVICE-CONN
#
# The following pipeline parameters have to be setted for manual execution:
# - SUBSCRIPTION: service connection name

parameters:
  - name: "SUBSCRIPTION"
    displayName: "Select the Azure subscription for which purge durable function history"
    type: string
    default: DEV-IO-SERVICE-CONN
    values:
      - PROD-IO-SERVICE-CONN
      - DEV-IO-SERVICE-CONN

pool:
  vmImage: "ubuntu-latest"

# Only manual execution from Azure DevOps portal
# trigger: none
trigger:
  - master
pr: none

jobs:
  - job: terraform_integrity_check
    steps:
      # 1. Set the number of the run
      - task: PowerShell@2
        displayName: Update Run Number
        inputs:
          targetType: "inline"
          script: '$id = "$(Build.BuildId)"; $date = Get-Date -Format "yyyy.MMdd"; Write-Host "##vso[build.updatebuildnumber]$date.$id"'

      # 2. Install terraform -> tfenv
      - task: AzureCLI@2
        displayName: Install terraform
        inputs:
          azureSubscription: "${{ parameters.SUBSCRIPTION }}"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          failOnStandardError: false
          inlineScript: |
            # git clone write on stderr https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-clone.html
            git clone https://github.com/tfutils/tfenv.git $HOME/.tfenv
            echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> $HOME/.bash_profile
            source $HOME/.bash_profile
            tfenv install

      # 3. Install teragrunt -> tgenv
      - task: AzureCLI@2
        displayName: Install teragrunt
        inputs:
          azureSubscription: "${{ parameters.SUBSCRIPTION }}"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          failOnStandardError: false
          inlineScript: |
            # git clone write on stderr https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-clone.html
            git clone https://github.com/cunymatthieu/tgenv.git $HOME/.tgenv
            echo 'export PATH="$HOME/.tgenv/bin:$PATH"' >> $HOME/.bash_profile
            source $HOME/.bash_profile
            tgenv install

      # 4. teragrunt plan
      - task: AzureCLI@2
        displayName: teragrunt plan
        inputs:
          azureSubscription: "${{ parameters.SUBSCRIPTION }}"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          failOnStandardError: false
          inlineScript: |
            ls -la $HOME/.ssh
            source $HOME/.bash_profile
            cd dev/westeurope/dev-pasquale-test/storage_account
            terragrunt plan
